### ISSUE TITLE
How to get the script running in the online mode?

### ISSUE THREAD

**Issue by JannyMon** [lgrahl/scripthookvpy3k#17]
As we know, the script example "NativeTrainer.asi" provided by Alexander Blade (the author of Script Hook V) can not run in the online mode. I'd like to if I use the GTALua engine; then can the script run in the online mode? Or how can I get the script to work in the online mode? I don't know the method. Can you share some?Need some specific methods.

**Comment by lgrahl** [comment]
I'm not the developer of GTALua. The Script Hook V doesn't work online on purpose because you'll get banned.
