### ISSUE TITLE
Is this still working in 2018?

### ISSUE THREAD

**Issue by nitanmarcel** [lgrahl/scripthookvpy3k#20]
I know that the project wasn't updated for a long time, but I'm wondering if it works with the latest version of Script Hook V

**Comment by lgrahl** [comment]
It might still work. :man_shrugging: Probably requires generating new bindings and perhaps updating of some examples.

**Comment by nitanmarcel** [comment]
@lgrahl gotta test it this sunday if I have time and report back if anything happens :)

**Comment by christopher-beckham** [comment]
@nitanmarcel any news? Thanks!

**Comment by lgrahl** [comment]
I think he filed #21 as a followup. I'll close this for now and you guys can open new issues if you encounter specific problems (such as #21).
